'use strict';
const escape = value => String(value).replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char]));
function renderSavedCardCheckout({ nonce, initialGrant = '' }) {
  const countries = require('country-state-city').Country.getAllCountries().map(country =>
    `<option value="${escape(country.isoCode)}">${escape(country.name)}</option>`).join('');
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Rozare · Secure saved-card payment</title>
<style nonce="${nonce}">*{box-sizing:border-box}body{margin:0;padding:22px;font-family:system-ui,sans-serif;color:#172435;background:linear-gradient(130deg,#eef8fa,#f0edff);min-height:100vh}.card{max-width:540px;margin:auto;padding:22px;background:#ffffffd9;border:1px solid #fff;border-radius:22px;box-shadow:0 12px 35px #283d6310}h1{font-size:23px;margin:8px 0}.muted{color:#62718a;font-size:14px;line-height:1.6}.badge{display:inline-block;border-radius:20px;padding:7px 12px;background:#edf4ff;font-size:12px;color:#535bea}.total{font-size:30px;font-weight:750;margin:12px 0}label{display:block;margin:13px 0;font-size:14px}input,select{display:block;width:100%;padding:12px;margin-top:6px;border-radius:12px;border:1px solid #d7ddec;background:#f9fbff;font:inherit}button{width:100%;border:0;border-radius:14px;padding:15px;margin-top:14px;color:white;font:inherit;font-weight:650;background:linear-gradient(115deg,#08b6ac,#6661f7)}button:disabled{opacity:.5}.secondary{background:#e9edf8;color:#46567b}.status{margin:14px 0;font-size:14px;line-height:1.6}#bank{min-height:520px}#bank[hidden],#form[hidden]{display:none}.row{display:grid;grid-template-columns:1fr 1fr;gap:12px}@media(max-width:400px){body{padding:12px}.card{padding:17px}.row{grid-template-columns:1fr}}</style>
<script nonce="${nonce}" src="/api/safepay/assets/atoms-0.3.7.js" defer></script></head><body><main class="card"><span id="badge" class="badge">Secure saved-card payment</span><h1>Review your payment</h1><p id="amount" class="total"></p><p id="card" class="muted"></p><p class="muted">Your card number and security code stay with Safepay. Your bank may ask you to verify this payment.</p><p id="status" class="status" role="status">Loading your verified payment…</p>
<form id="form" hidden><label>Billing street address<input id="street" autocomplete="billing street-address" required maxlength="200"></label><div class="row"><label>City<input id="city" autocomplete="billing address-level2" required maxlength="100"></label><label>State / Province<input id="state" autocomplete="billing address-level1" maxlength="100"></label></div><div class="row"><label>Country<select id="country" autocomplete="billing country" required><option value="">Select your country</option>${countries}</select></label><label>Postal code<input id="postal" autocomplete="billing postal-code" maxlength="20"></label></div><button id="pay" type="submit">Pay securely</button></form>
<div id="bank" hidden></div><button id="check" class="secondary" type="button" hidden>Return to Rozare and check payment</button></main>
<script nonce="${nonce}">(()=>{'use strict';const el=id=>document.getElementById(id);const ticket=new URLSearchParams(location.hash.slice(1)).get('ticket');const endpoint=location.pathname;let details=null,busy=false,sessionGrant=${JSON.stringify(initialGrant).replace(/</g, '\\u003c')},initialized=false;
const message=text=>{el('status').textContent=text};const request=async(path,body)=>{const response=await fetch(endpoint+path,{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+ticket,'X-Rozare-Checkout-Grant':sessionGrant},cache:'no-store',body:JSON.stringify(body||{})});const data=await response.json();if(!response.ok)throw new Error(data.msg||'Payment verification is unavailable. Close this screen and check this same payment in Rozare.');return data};
const returnToRozare=()=>{if(details&&details.returnUrl)location.replace(details.returnUrl)};el('check').onclick=returnToRozare;
const refreshContext=async(fillBilling=true)=>{const data=await request('/context');details=data;el('amount').textContent=new Intl.NumberFormat('en',{style:'currency',currency:data.currency}).format(data.amountMinor/100);el('card').textContent=data.card.brand+' ending '+data.card.last4;el('badge').textContent=data.environment==='sandbox'?'Safepay Sandbox · Test payment':'Secured by Safepay';if(fillBilling){el('street').value=data.billing.street_1;el('city').value=data.billing.city;el('state').value=data.billing.state;el('country').value=data.billing.country;el('postal').value=data.billing.postal_code}el('pay').textContent=(data.canRestartAuthentication?'Retry bank verification · ':'Pay ')+el('amount').textContent;el('pay').disabled=!data.canAuthenticate;el('check').hidden=false;el('form').hidden=!data.canAuthenticate;if(data.canAuthenticate)message(data.canRestartAuthentication?'The previous verification did not complete. Retry starts fresh bank verification for this same payment, card and amount.':'Review the amount and billing address, then approve this payment.');else message(data.authenticationInProgress?'Bank verification is being checked. Keep this same payment and return to Rozare to check its status before retrying.':'This payment has advanced. Return to Rozare to verify its current status.');return data};
el('form').onsubmit=async event=>{event.preventDefault();if(busy||!details||!details.canAuthenticate)return;busy=true;el('pay').disabled=true;message('Preparing secure bank verification…');try{if(!customElements.get('safepay-payer-auth-atom'))await Promise.race([customElements.whenDefined('safepay-payer-auth-atom'),new Promise((_,reject)=>setTimeout(()=>reject(new Error('Bank verification could not load. Keep this payment and try again.')),30000))]);const context=await request('/authenticate',{restartAuthentication:details.canRestartAuthentication===true,billing:{street_1:el('street').value,city:el('city').value,state:el('state').value,country:el('country').value,postal_code:el('postal').value}});details.returnUrl=context.returnUrl;el('form').hidden=true;el('bank').hidden=false;el('check').hidden=false;message('Complete any verification requested by your bank. Payment is confirmed only after Rozare verifies it.');const done=()=>{message('Checking the payment with Rozare…');returnToRozare()};const failed=()=>{message('Bank verification was not completed. Return to Rozare to check this same payment before retrying.');el('check').hidden=false};const payer=document.createElement('safepay-payer-auth-atom');Object.assign(payer,{environment:context.environment,tracker:context.tracker,authToken:context.authToken,user:context.user,billing:context.billing,deviceDataCollectionJWT:context.deviceDataCollectionJWT,deviceDataCollectionURL:context.deviceDataCollectionURL,authorizationOptions:{do_capture:true,do_card_on_file:false},onPayerAuthenticationSuccess:done,onPayerAuthenticationFrictionless:done,onPayerAuthenticationFailure:failed,onPayerAuthenticationUnavailable:failed,onSafepayError:failed});el('bank').replaceChildren(payer);}catch(error){message(error.message);el('check').hidden=false;try{const fresh=await refreshContext(false);if(fresh.canAuthenticate&&!fresh.canRestartAuthentication)message(error.message)}catch(_){el('pay').disabled=true;message('This payment screen could not be verified. Close it and reopen the same payment from Rozare.')}}finally{busy=false}};
if(!ticket){message('Open this secure payment screen from your Rozare account.');return}const initialize=()=>{if(initialized||!sessionGrant)return;initialized=true;refreshContext().catch(()=>message('This payment screen could not be verified or has expired. Close it and reopen the same payment from Rozare.'));};window.addEventListener('message',event=>{let allowed=false;try{const host=new URL(event.origin).hostname;allowed=event.origin.startsWith('https://')&&(host==='rozare.com'||host.endsWith('.rozare.com'))}catch(_){}if(!allowed||event.source!==window.parent||event.data?.type!=='rozare-saved-card-session'||event.data.paymentId!==endpoint.split('/').pop()||typeof event.data.grant!=='string')return;sessionGrant=event.data.grant;initialize()});if(sessionGrant)initialize();else if(window.parent!==window)window.parent.postMessage({type:'rozare-saved-card-ready',paymentId:endpoint.split('/').pop()},'*');else message('Open this secure screen inside your signed-in Rozare account. A copied link cannot use your saved card.');})();</script></body></html>`;
}
module.exports = { renderSavedCardCheckout };
