'use strict';
const router = require('express').Router();
const auth = require('../middleware/authMiddleware');
const { paymentStatusPollingLimiter, orderPaymentCreationLimiter, cardSetupCreationLimiter } = require('../middleware/paymentCreationLimiter');
const controller = require('../controllers/safepayController');
const billing = require('../controllers/safepayBillingController');
router.get('/return', controller.returnToApp);
router.get('/config', auth, controller.getConfig);
router.get('/cards', auth, paymentStatusPollingLimiter, controller.listCards);
router.post('/cards/setup', auth, cardSetupCreationLimiter, controller.startCardSetup);
router.patch('/cards/:cardId/default', auth, controller.setDefaultCard);
router.delete('/cards/:cardId', auth, controller.deleteCard);
router.get('/payments/:paymentId', auth, paymentStatusPollingLimiter, controller.getPayment);
router.post('/payments/:paymentId/reopen', auth, orderPaymentCreationLimiter, controller.reopenPayment);
router.post('/subscription/quote', auth, orderPaymentCreationLimiter, billing.quote);
router.post('/subscription/retry-quote', auth, orderPaymentCreationLimiter, billing.retryQuote);
router.patch('/subscription/card', auth, billing.changeCard);
router.post('/subscription/accept', auth, orderPaymentCreationLimiter, billing.accept);
router.get('/subscription/operations/:operationId', auth, paymentStatusPollingLimiter, billing.status);
router.post('/subscription/cancel', auth, billing.cancel);
router.post('/subscription/resume', auth, billing.resume);
router.post('/subscription/downgrade', auth, billing.downgrade);
router.post('/subscription/cancel-downgrade', auth, billing.cancelDowngrade);
router.post('/subdomain/purchase', auth, orderPaymentCreationLimiter, controller.purchaseSubdomain);
module.exports = router;
