import config from './commercePolicyConfig.json';

// Shared by the web and mobile app. Publication is blocked until the merchant
// confirms its address, public contact details and operational commitments.
export const policyConfig = config;
export const policyPublicationReady = config.publicationApproved === true
  && Boolean(config.registeredAddress && config.jurisdictionCity && config.supportPhone)
  && (config.sameOperatingAddress === true || Boolean(config.operatingAddress));
export const supportTimeline = `We acknowledge complaints within ${config.complaintAcknowledgementBusinessDays} business days and aim to resolve them within ${config.complaintResolutionTargetBusinessDays} business days. If seller, courier or payment-provider investigation takes longer, we explain the reason and next update. Business days are Monday to Friday, excluding public holidays in Pakistan.`;
export const refundTimeline = `We initiate an approved refund within ${config.approvedRefundInitiationBusinessDays} business days after approval and any required return inspection. A Rozare Wallet refund appears once funding is verified. An original-card refund may take additional time to appear because Safepay and the card-issuing bank process it separately. We provide the refund status or reference when available; contact support if it has not arrived within the timeframe given for your case. Business days exclude weekends and public holidays in Pakistan.`;

const section = (title, content) => ({ title, content });
export const commercePolicies = {
  terms: {
    title: 'Terms and Conditions', path: '/terms', screen: 'TermsOfService', icon: 'document-text-outline',
    description: 'The terms governing Rozare accounts, marketplace purchases, seller services and payment responsibilities.',
    sections: [
      section('1. About Rozare and contact details', `${config.tradingName} is the brand and trading name of ${config.legalName}, the owner and operator of ${config.website} and the Rozare platform, registered in Pakistan.${config.registeredAddress ? ` Registered business address: ${config.registeredAddress}.` : ''}${config.sameOperatingAddress === true ? ' The principal place of business is the same as the registered business address.' : config.operatingAddress ? ` Principal place of business: ${config.operatingAddress}.` : ''} Contact ${config.supportEmail}${config.supportPhone ? ` or ${config.supportPhone}` : ''} for order, payment and account support. General company inquiries: ${config.companyEmail}. These terms apply to the Rozare website, mobile app and supported messaging services.`),
      section('2. Agreement and accounts', 'Review these terms and the Privacy, Shipping and Delivery, Return and Refund, and Cancellation policies before placing an order or subscribing. Provide accurate account, billing and delivery details and protect your credentials. A person below the age of legal majority may use Rozare only with the permission and active involvement of a parent or legal guardian. We may restrict accounts that violate these terms, applicable law or safety rules.'),
      section('3. Marketplace and seller responsibilities', 'Rozare operates a multi-vendor e-commerce marketplace where approved sellers create stores and list products, and provides paid monthly subscriptions for store-management features. Products are subject to content checks and approval before publication. Physical products are fulfilled directly by the respective seller. Any digital product offered must clearly explain its content, access or delivery method and applicable terms before purchase; a physical shipping estimate does not describe digital fulfillment. The seller identified on the listing is responsible for the product, description, availability, fulfillment and applicable item-specific return policy. Sellers must supply lawful goods and accurate prices, delivery estimates and contact information. Customers purchase through Rozare, which facilitates payments, order tracking, returns and support. Contact Rozare if you cannot resolve an issue with a seller.'),
      section('4. Products, prices and order acceptance', 'Review the selected product options, quantity, seller, delivery method, currency, discounts and final amount before confirming. Prices and availability can change before checkout; the backend rechecks them. An order can contain several sellers, each with its own shipping charge, delivery estimate and fulfillment status. Order details identify each seller’s items. Payment or order processing may be declined for unavailable stock, unsupported delivery, invalid details or suspected fraud; any collected payment that cannot be applied is handled through the verified refund process.'),
      section('5. Payments and currency', 'New online card payments are handled by Safepay. Rozare also offers its Wallet and Cash on Delivery where eligible. A checkout uses one payment method and currency. If any seller does not accept Cash on Delivery, that method is unavailable for the full checkout. Prices in another currency are converted for checkout; the final payable amount and order currency are shown before payment and saved with the order. Safepay and your card issuer may apply their own rules or conversion charges. No separate Safepay account is required. Card data is entered in Safepay’s secure form, not sent to Rozare as raw card details. Sandbox or test-mode payments are demonstrations, not live customer charges.'),
      section('6. Seller subscriptions and saved cards', 'Seller subscription prices, currency, free-period eligibility, recurring amount and any add-ons are displayed before confirmation. Saving a card alone does not subscribe you. A recurring plan requires your explicit agreement to the displayed price and renewal terms. Cancel automatic renewal from Seller Dashboard → Subscription before the next billing date. Access continues until the end of the applicable period. Plan changes may involve a disclosed prorated charge or credit; review the quote before agreeing. Cancelling renewal is not an automatic refund of past charges. Report duplicate, incorrect or unauthorized charges to support promptly; mandatory legal rights remain unaffected.'),
      section('7. Delivery, returns and cancellations', 'The Shipping and Delivery, Return and Refund, and Cancellation policies form part of these terms. Item-specific eligibility and delivery terms are shown with the product and order. A seller policy does not remove rights you have under applicable consumer law. Closing a payment window does not itself cancel an order or prove that payment failed. Check the verified payment and order status before paying again.'),
      section('8. Governing law and jurisdiction', `These terms are governed by the laws of the Islamic Republic of Pakistan. ${config.jurisdictionCity ? `The competent courts of ${config.jurisdictionCity}${config.jurisdictionProvince ? `, ${config.jurisdictionProvince}` : ''}, Pakistan, including applicable consumer courts where required by law, have jurisdiction over disputes arising from these terms.` : 'Disputes are subject to the jurisdiction of the competent courts in Pakistan, including the relevant consumer court.'} Nothing in these terms excludes mandatory consumer rights or prevents you from using a forum or remedy available under applicable law.`),
      section('9. Acceptable use and intellectual property', 'Do not list illegal, counterfeit or prohibited goods, use abusive or prohibited seller content, commit fraud, impersonate others, harass users, or interfere with platform security. Rozare may moderate, restrict or remove violating content. Rozare and its licensors own the platform software, branding and designs. You retain rights in content you upload and grant the permissions needed to host, display and operate it through the platform.'),
      section('10. Complaints and dispute assistance', `Email ${config.supportEmail}${config.supportPhone ? ` or call ${config.supportPhone}` : ''} with your order or subscription reference, contact details and a clear description of the problem. Do not send passwords, full card numbers, security codes or OTPs. ${supportTimeline}`),
      section('11. Responsibility and statutory rights', 'Rozare aims to provide a reliable service but cannot guarantee uninterrupted access or delivery events outside its control. Each party remains responsible for its own obligations and for liability that cannot lawfully be excluded. These terms do not exclude responsibility for fraud or remove a customer’s mandatory rights concerning faulty goods, non-delivery, refunds or other applicable protections.'),
      section('12. Updates to these terms', 'We publish the current version and update date here and notify users of material changes where required. The order and billing terms accepted for an existing purchase remain relevant to that transaction; new terms do not silently rewrite its saved price, currency or payment agreement.'),
    ],
  },
  shipping: {
    title: 'Shipping and Delivery Policy', path: '/shipping-policy', screen: 'ShippingPolicy', icon: 'car-outline',
    description: 'Seller fulfillment, delivery estimates, shipping costs and multi-seller tracking on Rozare.',
    sections: [
      section('Who delivers your products', 'Physical products are packed and fulfilled directly by the seller shown on the listing and order. Rozare provides the marketplace and order tracking. Products from different sellers may be sent as separate shipments and arrive on different days.'),
      section('Digital products and platform services', 'Physical shipping methods and courier estimates do not apply to digital products or seller subscription services. Where a digital product is offered, review its stated access or delivery method and expected availability before purchase and contact the seller or Rozare if it is not supplied as described. Subscription features are enabled only after the applicable enrollment or payment is verified. This policy does not promise automatic file downloads where that feature is not available.'),
      section('Delivery areas and international availability', 'Delivery depends on the seller’s coverage and your actual delivery address. A Global browsing selection helps discovery; it is not a promise that every product can be delivered to every address. Local and international availability must be supported by the seller and confirmed at checkout. Verify any import duties, destination restrictions or additional requirements with the seller before ordering; costs not included in checkout must not be represented as already paid.'),
      section('Shipping charges and turnaround time', 'Each seller sets available shipping methods, prices and estimated delivery days. Rozare displays the available cost and delivery estimate for each seller at checkout before you pay, including a zero charge when the method is free. There is no single platform-wide delivery time: Standard, Express and Free are method names, not fixed guarantees. Review the quoted estimate and ask the seller if processing time or an international route is unclear before placing the order. Your order retains the selected method, charge and estimate.'),
      section('Address details and tracking', 'Provide the complete delivery address and a reachable phone number. Track each seller’s items in My Orders; seller status updates apply to that seller’s shipment. A single purchase with several sellers is not automatically delivered when the first shipment arrives. Contact the seller or support promptly about an incorrect address, missed delivery, missing parcel or delay beyond the quoted estimate. Address changes after fulfillment begins may not be possible.'),
      section('Delays, damage and non-delivery', `Delivery estimates may be affected by courier, customs, holidays, weather or other disruptions. Report damaged, incorrect or missing items with the order number and relevant evidence to the seller and ${config.supportEmail}. Do not mark an undelivered item as received. See the Return and Refund Policy for available remedies; a delivery delay does not remove mandatory consumer rights.`),
    ],
  },
  refunds: {
    title: 'Return and Refund Policy', path: '/refund-policy', screen: 'RefundPolicy', icon: 'return-down-back-outline',
    description: 'Return eligibility, refund methods, processing times and how to get help with a refund.',
    sections: [
      section('Return eligibility', 'Review the return terms shown for the item before purchasing. Each seller or product specifies whether returns are offered, the request window after delivery, and whether the available resolution is a Wallet refund or replacement. The order retains the applicable policy. Submit the request within that window after the relevant seller’s items are delivered. Store-specific exclusions do not remove rights under applicable law for faulty, misdescribed or undelivered goods.'),
      section('How to request a return', 'Open My Orders → Order Details, select the eligible seller’s items and quantity, and submit the reason and any requested evidence. Follow the return instructions recorded for the case; do not send products to Rozare’s registered office unless support specifically instructs you to. Pickup, return shipping responsibility and inspection requirements are handled with the seller and must be explained before you dispatch the return. Use support if the request button is unavailable and you believe a legal remedy is due.'),
      section('Refund amount and destination', 'For the standard in-app return process, an approved refund is credited to your Rozare Wallet in the saved order currency after the seller’s funding is verified. It is not automatically sent to the original card or paid as cash. The case shows the approved amount; it is limited to the eligible items and their applicable tax, discount and shipping allocation, less any amount already refunded. A replacement-only resolution does not also create a money refund. Contact support before agreeing to a Wallet resolution if you require a different remedy or applicable law entitles you to one.'),
      section('Card-payment reversals and payment errors', 'When a Safepay card payment cannot be applied to its intended purchase, Rozare verifies the payment outcome and uses the applicable original-payment refund or review process. An order cancellation or closed payment window alone does not prove that a refund was issued. Duplicate, incorrect or unauthorized charges should be reported to support with the order or payment reference. Never send full card details, CVV, passwords or OTPs. Card refunds and Wallet credits are different destinations and will be identified in your case.'),
      section('Refund processing turnaround time', refundTimeline),
      section('Subscriptions, Wallet top-ups and services', 'Cancelling a subscription stops future renewal according to the Cancellation Policy; it does not automatically refund a used subscription period. Wallet top-ups are credits for use on Rozare, not a bank deposit or seller withdrawal balance. Contact support about mistaken, duplicate or unauthorized top-ups or service charges. Refund eligibility is assessed against the transaction and applicable law; we do not promise unconditional refunds or automatic cash withdrawal of Wallet credits.'),
      section('Refund delays and complaints', `Contact ${config.supportEmail}${config.supportPhone ? ` or ${config.supportPhone}` : ''} with your order number, return reference and the date of approval if a refund is delayed. We check the seller funding and provider status and give you an update. ${supportTimeline}`),
    ],
  },
  cancellation: {
    title: 'Cancellation Policy', path: '/cancellation-policy', screen: 'CancellationPolicy', icon: 'close-circle-outline',
    description: 'How to cancel eligible orders, stop subscription renewals and understand payment-window closure.',
    sections: [
      section('Cancelling an unpaid order before shipment', 'Open My Orders → Order Details and choose Cancel while the order is eligible. The server checks the current payment and fulfillment state. An unpaid order can be cancelled before any seller’s portion has shipped or been delivered. Where a valid COD confirmation message offers Cancel, it uses the same eligibility checks. A previous confirmation does not prevent an otherwise eligible unpaid, unshipped order from being cancelled.'),
      section('Paid, shipped and multi-seller orders', 'Paid orders require a verified refund and cannot be immediately cancelled through the unpaid-order button. Contact support promptly before shipment to request assistance. If any seller’s items have shipped or been delivered, whole-order cancellation is no longer available; use the return process for eligible delivered items and contact support about other affected items. Do not assume one seller’s cancellation or shipment changes every other seller’s items.'),
      section('Closing Safepay checkout', 'Closing checkout or returning from Safepay without completing the form does not cancel the order, erase the payment attempt or prove that money was not collected. Reopen the same attempt or check its status from Rozare before starting another payment. If an old link is later paid, Rozare rechecks the associated order, stock and eligibility; the payment is applied only when still valid, otherwise it goes through the verified refund or review process. Do not pay a cancelled order’s old link.'),
      section('Cancellation by a seller or Rozare', 'An order may be declined or cancelled for unavailable stock, inability to deliver, safety restrictions, invalid details or suspected fraud. A paid order must be reconciled and refunded where due rather than simply marked unpaid. Check your order status and contact support if funds were collected but no valid purchase or refund is recorded.'),
      section('Stopping subscription renewals', 'Open Seller Dashboard → Subscription and confirm cancellation before the next billing date. Your plan remains available until the current trial, introductory or paid period ends, as shown on the page. Automatic renewal then stops. Cancellation does not automatically refund previous subscription payments or delete the store’s data. Any founder-rate or bonus eligibility consequences are shown before you confirm. An eligible scheduled downgrade takes effect at period end and can be undone before it begins.'),
      section('Getting help', `Email ${config.supportEmail}${config.supportPhone ? ` or call ${config.supportPhone}` : ''} with the order or subscription reference. Cancellation requests are checked against the latest payment and shipping status; sending a message alone is not confirmation of cancellation. See the Return and Refund Policy for refund destinations and processing times. ${supportTimeline}`),
    ],
  },
};
